### ISSUE TITLE
ASL Perf support

### ISSUE THREAD

**Issue by dkp** [brainlife/ezbids#66] opened 2022-09-19 00:08 UTC
Dear EZ-Bids creators,

I have three ASL files: (1) A single TI PASL scan with M0 included, (2) a Multi-TI PASL scan with no M0 scan, and (3) a separate M0scan to accompany the multiTI sequence.  EZ-BIDS recognizes these as ASL scans, but provides no additional fields that can be used to distinguish the single and multi-TI acquisitions.  

In addition, the only choice for the m0scan is to treat it as a field map, but this is not appropriate because it is simply being used for calibration and not pepolar distortion correction.  

Do you plan to provide more comprehensive support for ASL data?

**Comment by dlevitas** [comment] 2022-09-19 13:07
Hi @dkp ,

> Do you plan to provide more comprehensive support for ASL data?

Yes, this is something we can do. We aren't as familiar with non-MRI imaging modalities, so for improved support for modalities such as ASL, we ask users/collaborators if they are willing to share DICOMs or dcm2niix-generated files, for testing and validations purposes. Would you be willing to share these ASL files?

Thanks

**Comment by dkp** [comment] 2022-09-19 16:49
Hi @dlevitas, 
See the MRI dataset including the Arterial Spin Labeling scans here: https://osf.io/hxz8t
I've attached a Markdown document that explains the data and the corresponding BIDS Arterial Spin Labeling specification.  The document specifically walks through converting the PASL data I've included on OSF, and not all variants of ASL data: [BIDS_ASL.md](https://github.com/brainlife/ezbids/files/9600834/BIDS_ASL.md)

Thank you for your willingness to look into this!  I'm excited.

-Dianne

**Comment by dlevitas** [comment] 2022-09-19 17:26
Thanks for the data and documentation, @dkp!

It will likely be several weeks before we've included and validated the ASL ingestion, but we'll let you know once it's ready.

**Comment by dkp** [comment] 2022-09-19 18:13
Thanks so much!  EZ-BIDS is a great project.

**Comment by dlevitas** [comment] 2023-05-04 19:13
Hi @dkp I wanted to get your input regarding a potential feature enhancement that will potentially allow us to fully support ASL sequences.

For context (#80), we're working on integrating PET support into ezBIDS. The problem is that PET dicoms don't contain all the necessary fields required by BIDS in the json sidecars to pass validation. The potential feature would allow users to separately upload spreadsheets (.tsv, .csv, .xlsx) with this information, which would then be injected into the appropriate sidecars. Something like this:
![Screen Shot 2023-05-04 at 3 01 19 PM](https://user-images.githubusercontent.com/25011343/236303332-68faf4a5-de4c-4552-b278-e88bf5410c30.png)

In your ASL tutorial, you use `gdcmdump` to peruse the DICOM headers for this information; however, I worry not all scanner manufactures provide this information.  Given that PET, ASL, and presumably other imaging modalities have this underlying problem, this "injection" workflow may have broad utility. I was curious whether it's common practice for researchers using ASL to store this metadata in a similar fashion, and whether you think this feature enhancement make intuitive sense?

**Comment by dkp** [comment] 2023-05-04 20:01
Hi Dan,

I like the idea very much!  Siemens hides some of the information we want in proprietary fields, hence gdcmdump. But I understand that more of it will be available in the future in the DICOM headers.  At the very least, people should be able to get the parameters they need from their technician or from a printout of their protocol.

I've been playing with BIDScoin which makes a similar choice, but in their GUI (see page 11 of 19 in the attached pdf). They provide all of the required BIDS key fields for the ASL modality, and once you fill those in, they'll apply to all subjects you run in the future. [BIDScoin Slides.pdf](https://github.com/brainlife/ezbids/files/11401046/BIDScoin.Slides.pdf)

A significant difficulty for me in ezBIDS is that **I don't see any way to save and reuse a configuration file**.
The point is, I believe people should be looking at their data and converting it as they go along.  ezBIDS requires you to recreate all of your choices every time!  It seems like your spreadsheet idea is a step in the direction of being able to save and reuse configuration information!  

I'm a fan!

**Comment by dlevitas** [comment] 2023-05-04 20:17
Thanks @dkp!

Your concern about a lack of a reusable configuration file for ezBIDS mirrors some recent discussions we've had on the topic. I agree, a long-term goal of ezBIDS will be to enable a pre-specified configuration. Thanks again for your quick response, we'll keep you updated on these changes.

**Comment by dkp** [comment] 2023-05-29 20:53
@dlevitas sorry I missed this!  Yes, fields like BolusCutOffDelayTime are part of the MR protocol and therefore applied consistently across subjects.

**Comment by dlevitas** [comment] 2023-11-02 16:21
Completed, as of PR #99. Closing this issue now.

**Closed by dlevitas** 2023-11-02 16:21 UTC
